export { SearchService } from "./search.service";
export { SearchController } from "./search.controller";
export * from "./search.types";
export {
  // Core schemas
  searchItemTypeSchema,
  searchFilterSchema,
  searchQueryRequestSchema,
  contentSearchSchema,
  mediaSearchSchema,
  userSearchSchema,
  // Index schemas
  indexDocumentSchema,
  bulkIndexSchema,
  deleteFromIndexSchema,
  bulkDeleteFromIndexSchema,
  reindexSchema,
  // Configuration schemas
  searchConfigSchema,
  searchAggregationSchema,
  // Response schemas
  searchResultItemSchema,
  searchResultSchema,
  searchStatsSchema,
  indexStatusSchema,
  searchSuggestionSchema,
  suggestionResultSchema,
  searchAnalyticsSchema,
  // Endpoint schemas
  searchEndpoint,
  searchContentEndpoint,
  searchMediaEndpoint,
  searchUsersEndpoint,
  indexDocumentEndpoint,
  bulkIndexEndpoint,
  deleteFromIndexEndpoint,
  bulkDeleteFromIndexEndpoint,
  reindexEndpoint,
  getSearchStatsEndpoint,
  getSuggestionsEndpoint,
  updateSearchConfigEndpoint,
  trackSearchAnalyticsEndpoint,
  // Response type schemas
  searchResultResponseSchema,
  searchStatsResponseSchema,
  indexStatusResponseSchema,
  suggestionResultResponseSchema,
  searchConfigResponseSchema,
  indexOperationResponseSchema,
  // Schema-specific types to avoid conflicts
  type SearchItemType,
  type SearchQueryRequest,
  type ContentSearchRequest,
  type MediaSearchRequest,
  type UserSearchRequest,
  type BulkIndexRequest,
  type DeleteFromIndexRequest,
  type BulkDeleteFromIndexRequest,
  type ReindexRequest,
  type SearchAggregation,
  type SearchResultItem,
  type SearchSuggestion,
  type SuggestionResult,
  type SearchResultResponse,
  type SearchStatsResponse,
  type IndexStatusResponse,
  type SuggestionResultResponse,
  type SearchConfigResponse,
} from "./search.schemas";
