# Grafana Helm chart values

# Admin user
adminUser: admin
adminPassword: "${GRAFANA_ADMIN_PASSWORD}"

# Persistence
persistence:
  enabled: true
  size: 10Gi

# Resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Service
service:
  type: ClusterIP
  port: 80

# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - grafana.${DOMAIN_NAME}
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.${DOMAIN_NAME}

# Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
      - name: Tempo
        type: tempo
        url: http://tempo:3100
        access: proxy

# Dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    # Node Exporter Dashboard
    node-exporter:
      gnetId: 1860
      revision: 21
      datasource: Prometheus
    
    # Kubernetes Cluster Dashboard
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    
    # API Gateway Dashboard
    api-gateway:
      url: https://grafana.com/api/dashboards/13223/revisions/1/download
      datasource: Prometheus
    
    # PostgreSQL Dashboard
    postgresql:
      gnetId: 9628
      revision: 7
      datasource: Prometheus
    
    # Redis Dashboard
    redis:
      gnetId: 763
      revision: 4
      datasource: Prometheus
    
    # Kafka Dashboard
    kafka:
      gnetId: 7589
      revision: 5
      datasource: Prometheus
    
    # Custom SaaS Platform Dashboard
    saas-platform:
      file: dashboards/saas-platform.json

# Plugins
plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel
  - grafana-kubernetes-app
  - grafana-polystat-panel
  - natel-discrete-panel
  - vonage-status-panel
  - jdbranham-diagram-panel

# SMTP configuration for alerts
smtp:
  enabled: true
  host: "${SMTP_HOST}"
  user: "${SMTP_USER}"
  password: "${SMTP_PASSWORD}"
  fromAddress: "grafana@${DOMAIN_NAME}"
  fromName: "Grafana Alerts"

# Alerting
alerting:
  enabled: true
  # Default alert notification channels
  notifiers:
    - name: Email
      type: email
      uid: email
      org_id: 1
      is_default: true
      settings:
        addresses: "${ALERT_EMAIL_ADDRESSES}"
    - name: Slack
      type: slack
      uid: slack
      org_id: 1
      is_default: false
      settings:
        url: "${SLACK_WEBHOOK_URL}"
        recipient: "#alerts"
        mentionChannel: "here"
        mentionUsers: ""
        mentionGroups: ""
        token: "${SLACK_API_TOKEN}"
        iconEmoji: ":grafana:"
        username: "Grafana Alerts"
        uploadImage: true
