# Tempo Helm chart values

# Global settings
global:
  image:
    repository: grafana/tempo
    tag: 1.5.0

# Persistence
persistence:
  enabled: true
  size: 50Gi

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Service
service:
  type: ClusterIP
  port: 3100

# Configuration
tempo:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
    zipkin:
      endpoint: 0.0.0.0:9411
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    opencensus:
      endpoint: 0.0.0.0:55678
  
  distributor:
    receivers:
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      opencensus:
        endpoint: 0.0.0.0:55678
  
  ingester:
    trace_idle_period: 10s
    max_block_bytes: 1_000_000
    max_block_duration: 5m
  
  compactor:
    compaction:
      block_retention: 48h
  
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      pool:
        max_workers: 100
        queue_depth: 10000
  
  server:
    http_listen_port: 3100
  
  metrics_generator:
    registry:
      external_labels:
        source: tempo
        cluster: saas-platform
    storage:
      path: /var/tempo/generator/wal
      remote_write:
        - url: http://prometheus-server/api/v1/write
          send_exemplars: true
    processor:
      service_graphs:
        enabled: true
      span_metrics:
        enabled: true
        dimensions:
          - name: service
          - name: span_name
          - name: status_code
